// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tetpfwhzydrcoseyvhaw.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRldHBmd2h6eWRyY29zZXl2aGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0MzEwMDQsImV4cCI6MjA0OTAwNzAwNH0.zqALTcZ-z_Y7up__eME2Q7ZkY1wroH0i2SsyLdG1EyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);